use semtree_grammar::Grammar;
use smol_str::SmolStr;

/// Generate Rust source code for typed AST wrappers from a Grammar IR.
///
/// This produces a string of Rust code with one struct per rule and typed
/// accessor methods for fields, like rust-analyzer's ast module.
pub fn generate_ast(grammar: &Grammar) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by semtree_ast::codegen.\n");
    out.push_str("// Do not edit manually.\n\n");
    out.push_str("use semtree_core::SyntaxKind;\n");
    out.push_str("use semtree_red::{SyntaxNode, SyntaxToken};\n");
    out.push_str("use semtree_ast::{AstNode, AstChildren};\n\n");

    for (name, rule) in &grammar.rules {
        let struct_name = to_pascal_case(name);
        let kind_hash = rule_name_to_kind_value(name);

        // Struct definition
        out.push_str(&format!(
            "#[derive(Debug, Clone)]\npub struct {struct_name} {{\n    syntax: SyntaxNode,\n}}\n\n"
        ));

        // AstNode impl
        out.push_str(&format!(
            "impl AstNode for {struct_name} {{\n\
             \x20   fn kind() -> SyntaxKind {{ SyntaxKind({kind_hash}) }}\n\n\
             \x20   fn cast(node: SyntaxNode) -> Option<Self> {{\n\
             \x20       if node.kind() == SyntaxKind({kind_hash}) {{\n\
             \x20           Some(Self {{ syntax: node }})\n\
             \x20       }} else {{\n\
             \x20           None\n\
             \x20       }}\n\
             \x20   }}\n\n\
             \x20   fn syntax(&self) -> &SyntaxNode {{\n\
             \x20       &self.syntax\n\
             \x20   }}\n\
             }}\n\n"
        ));

        // Typed accessors for fields
        if !rule.fields.is_empty() {
            out.push_str(&format!("impl {struct_name} {{\n"));
            for field in &rule.fields {
                let accessor_name = to_snake_case(&field.name);
                let field_type = to_pascal_case(&field.rule);
                let field_kind_hash = rule_name_to_kind_value(&field.rule);

                // Check if the field type is a terminal.
                if is_terminal(&field.rule) {
                    out.push_str(&format!(
                        "\x20   pub fn {accessor_name}(&self) -> Option<SyntaxToken> {{\n\
                         \x20       self.syntax.child_token(SyntaxKind::IDENT)\n\
                         \x20   }}\n\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "\x20   pub fn {accessor_name}(&self) -> Option<{field_type}> {{\n\
                         \x20       self.syntax.child_node(SyntaxKind({field_kind_hash}))\n\
                         \x20           .and_then({field_type}::cast)\n\
                         \x20   }}\n\n"
                    ));
                }
            }
            out.push_str("}\n\n");
        }
    }

    out
}

fn rule_name_to_kind_value(name: &str) -> u16 {
    let mut hash: u16 = 4096;
    for (i, b) in name.bytes().enumerate() {
        hash = hash.wrapping_add(b as u16).wrapping_mul(31).wrapping_add(i as u16);
    }
    if hash < 4096 {
        hash += 4096;
    }
    hash
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().to_string() + &chars.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(c.to_lowercase().next().unwrap_or(c));
    }
    result
}

fn is_terminal(name: &str) -> bool {
    matches!(
        name,
        "Identifier" | "identifier" | "Integer" | "integer" | "String" | "string" | "Float" | "float"
    )
}
