use semtree_grammar::Grammar;

/// Generate Rust source code for typed AST wrappers from a Grammar IR.
///
/// This produces a string of Rust code with one struct per rule and typed
/// accessor methods for fields, like rust-analyzer's ast module.
pub fn generate_ast(grammar: &Grammar) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by semtree_ast::codegen.\n");
    out.push_str("// Do not edit manually.\n\n");
    out.push_str("use semtree_core::SyntaxKind;\n");
    out.push_str("use semtree_red::{SyntaxNode, SyntaxToken};\n");
    out.push_str("use semtree_ast::{AstNode, AstChildren};\n\n");

    for (name, rule) in &grammar.rules {
        let struct_name = to_pascal_case(name);
        let kind_hash = rule_name_to_kind_value(name);

        // Struct definition
        out.push_str(&format!(
            "#[derive(Debug, Clone)]\npub struct {struct_name} {{\n    syntax: SyntaxNode,\n}}\n\n"
        ));

        // AstNode impl
        out.push_str(&format!(
            "impl AstNode for {struct_name} {{\n\
             \x20   fn kind() -> SyntaxKind {{ SyntaxKind({kind_hash}) }}\n\n\
             \x20   fn cast(node: SyntaxNode) -> Option<Self> {{\n\
             \x20       if node.kind() == SyntaxKind({kind_hash}) {{\n\
             \x20           Some(Self {{ syntax: node }})\n\
             \x20       }} else {{\n\
             \x20           None\n\
             \x20       }}\n\
             \x20   }}\n\n\
             \x20   fn syntax(&self) -> &SyntaxNode {{\n\
             \x20       &self.syntax\n\
             \x20   }}\n\
             }}\n\n"
        ));

        // Typed accessors for fields
        if !rule.fields.is_empty() {
            out.push_str(&format!("impl {struct_name} {{\n"));
            for field in &rule.fields {
                let accessor_name = to_snake_case(&field.name);
                let field_type = to_pascal_case(&field.rule);
                let field_kind_hash = rule_name_to_kind_value(&field.rule);

                // Check if the field type is a terminal.
                if is_terminal(&field.rule) {
                    out.push_str(&format!(
                        "\x20   pub fn {accessor_name}(&self) -> Option<SyntaxToken> {{\n\
                         \x20       self.syntax.child_token(SyntaxKind::IDENT)\n\
                         \x20   }}\n\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "\x20   pub fn {accessor_name}(&self) -> Option<{field_type}> {{\n\
                         \x20       self.syntax.child_node(SyntaxKind({field_kind_hash}))\n\
                         \x20           .and_then({field_type}::cast)\n\
                         \x20   }}\n\n"
                    ));
                }
            }
            out.push_str("}\n\n");
        }
    }

    out
}

fn rule_name_to_kind_value(name: &str) -> u16 {
    let mut hash: u16 = 4096;
    for (i, b) in name.bytes().enumerate() {
        hash = hash.wrapping_add(b as u16).wrapping_mul(31).wrapping_add(i as u16);
    }
    if hash < 4096 {
        hash += 4096;
    }
    hash
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().to_string() + &chars.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(c.to_lowercase().next().unwrap_or(c));
    }
    result
}

fn is_terminal(name: &str) -> bool {
    matches!(
        name,
        "Identifier" | "identifier" | "Integer" | "integer" | "String" | "string" | "Float" | "float"
    )
}

/// Generate a Visitor trait from a Grammar IR.
///
/// Produces a trait with `visit_*` methods for each rule, plus a default
/// `walk` implementation that traverses children.
pub fn generate_visitor(grammar: &Grammar) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated visitor by semtree_ast::codegen.\n\n");

    // Visitor trait
    out.push_str("pub trait Visitor {\n");
    for name in grammar.rules.keys() {
        let fn_name = to_snake_case(name);
        let type_name = to_pascal_case(name);
        out.push_str(&format!(
            "    fn visit_{fn_name}(&mut self, node: &{type_name}) {{\n\
             \x20       self.walk_{fn_name}(node);\n\
             \x20   }}\n\n"
        ));
    }
    out.push_str("    // Walk methods (default traversal)\n");
    for (name, rule) in &grammar.rules {
        let fn_name = to_snake_case(name);
        let type_name = to_pascal_case(name);
        out.push_str(&format!(
            "    fn walk_{fn_name}(&mut self, node: &{type_name}) {{\n"
        ));
        for field in &rule.fields {
            let field_fn = to_snake_case(&field.name);
            let field_visit = to_snake_case(&field.rule);
            if !is_terminal(&field.rule) {
                out.push_str(&format!(
                    "        if let Some(child) = node.{field_fn}() {{\n\
                     \x20           self.visit_{field_visit}(&child);\n\
                     \x20       }}\n"
                ));
            }
        }
        out.push_str("    }\n\n");
    }
    out.push_str("}\n\n");

    // Rewriter trait
    out.push_str("pub trait Rewriter {\n");
    out.push_str("    fn rewrite_node(&mut self, node: &semtree_red::SyntaxNode) -> Option<String>;\n");
    out.push_str("}\n");

    out
}

/// Generate a CLI-friendly grammar summary.
pub fn grammar_summary(grammar: &Grammar) -> String {
    let mut out = String::new();
    out.push_str(&format!("Language: {}\n", grammar.name));
    out.push_str(&format!("Rules: {}\n", grammar.rules.len()));
    out.push_str(&format!("Keywords: {}\n", grammar.keywords.len()));
    out.push_str(&format!("Format hints: {}\n\n", grammar.format_hints.len()));

    out.push_str("Rules:\n");
    for (name, rule) in &grammar.rules {
        let fields: Vec<_> = rule.fields.iter().map(|f| format!("{}: {}", f.name, f.rule)).collect();
        if fields.is_empty() {
            out.push_str(&format!("  {name}\n"));
        } else {
            out.push_str(&format!("  {name} ({})\n", fields.join(", ")));
        }
    }

    if !grammar.keywords.is_empty() {
        out.push_str("\nKeywords: ");
        out.push_str(&grammar.keywords.iter().map(|k| k.as_str()).collect::<Vec<_>>().join(", "));
        out.push('\n');
    }

    out
}
