mod init;
mod parse;
mod run;
mod check;
mod format;
mod query;
mod lint;
mod symbols;
mod benchmark;
mod import;
mod doctor;
mod generate;
mod test;
mod migrate;

pub use init::init;
pub use parse::parse;
pub use run::run;
pub use check::check;
pub use format::format;
pub use query::query;
pub use lint::lint;
pub use symbols::symbols;
pub use benchmark::benchmark;
pub use import::import;
pub use doctor::doctor;
pub use generate::generate;
pub use test::test;
pub use migrate::migrate;

pub type Result = std::result::Result<(), Box<dyn std::error::Error>>;
