mod benchmark;
mod check;
mod doctor;
mod format;
mod generate;
mod import;
mod init;
mod lint;
mod migrate;
mod parse;
mod query;
mod run;
mod symbols;
mod test;

pub use benchmark::benchmark;
pub use check::check;
pub use doctor::doctor;
pub use format::format;
pub use generate::generate;
pub use import::import;
pub use init::init;
pub use lint::lint;
pub use migrate::migrate;
pub use parse::parse;
pub use query::query;
pub use run::run;
pub use symbols::symbols;
pub use test::test;

pub type Result = std::result::Result<(), Box<dyn std::error::Error>>;
